# Generated by Django 5.2.6 on 2026-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djangoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="carmodel",
            name="dealer_id",
            field=models.IntegerField(default=1),
        ),
    ]
